language: node_js
sudo: false
node_js:
- 5.0.0
install:
- npm install
script:
- "./node_modules/.bin/gulp"
notifications:
  slack:
    secure: qwLE5e4oKeptSNvn7Cq2yDb+ye9tVCiC+joWqi70jJb3bYJumzWYJ3lOaDceud3hnAxaV1s633BlwG4gSw4kQYvy/X/1z1Pi+QzXTvWOk79DY9YQyvIelGkAgS7Up7EX4tyCl79GcNvGE8Xhyl8JWE2BZKp2mFLWL6dGPx+gX74H0hLTQp4oZXa45jxfcDt8XYrLMijGdlpKa0G+PUkl1n/fpOjso9FQShvj+5NKq18IUDawY4nBCGUjx1l0lXD51CWAsKdvKS6YMna0WGLM7dmNepRuyaDzmMN4VbiZMs4/KbdBhLyqn9GW3rpQiA381jlJW7wjG+6IWxiRNGulza3SDvxwXsf5zaqZBSm3SprG0EIOigytUjv54LAPocwoJHdxQei/iecUL75u8y98JkPzgo7RSXwcN3hRPGLc0s5xPqQMqESLdtcfjhEPTvZuCkswhkVvNmXrN8ms9n4LPVzz7+Mve9DWBc/vohnX/psA9yEMb7sbvbZi7LUguX5L0bd/sT1S+STqKfzXBMX8bTaMQZgor7ODOqrmESK33wK4kwsyNQz7cjOr816qt/uD7G961KA5iOHLeXu/Erxa/8j6mlXjS44NOa5azoJBw0yIWBQd2s34qGJ/Gu26/sQHxtanamuut9/V460K/qSL9FjJkhRxS3bdCPybiXm5N7E=
